version: '3.7'

services:
  backend:
    image: "trollbot-be"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "trollbot-fe"
    ports:
      - "3000:3000"
    links:
      - "backend:be"
