services: 
  trollbot:
    ports:
      - 3001:3001
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: vornsami/trollbot
    hostname: trollbot
    env_file: .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - trollbot-rasa

  trollbot-rasa:
    ports:
      - 5055:5055
      - 5005:5005
    restart: unless-stopped
    build: ./backend/rasa
    image: vornsami/trollbot-rasa
    hostname: trollbot-rasa
    env_file: .env.rasa

volumes:
  logs:
