services: 
  trollbot:
    ports:
      - 3001:3001
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: trollbotproject/trollbot
    hostname: trollbot
    env_file: .env
    environment:
      - RASA_NETWORK=http://trollbot-rasa
    volumes:
      - ./logs:/usr/src/logs
    depends_on:
      - trollbot-rasa

  trollbot-rasa:
    restart: unless-stopped
    build: ./backend/rasa
    image: trollbotproject/trollbot-rasa
    hostname: trollbot-rasa
    env_file: .env.rasa
    environment:
      - BACKEND_API_LOCATION=trollbot:3001
      - ACTION_ENDPOINT_URL=http://trollbot-rasa:5055/webhook

volumes:
  logs:
