
/*
 * This file contains all of the socket events in one place. If for some reason the event name needs to be changed, it can be done here. (without needing to change the name of the variable)
 */

const USER_JOIN_CHAT_EVENT = 'USER_JOIN_CHAT_EVENT'
const USER_LEAVE_CHAT_EVENT = 'USER_LEAVE_CHAT_EVENT'
const NEW_CHAT_MESSAGE_EVENT = 'NEW_CHAT_MESSAGE_EVENT'
const SEND_MESSAGE_TO_BOT_EVENT = 'SEND_MESSAGE_TO_BSERVER_EVENT'
const START_TYPING_MESSAGE_EVENT = 'START_TYPING_MESSAGE_EVENT'
const STOP_TYPING_MESSAGE_EVENT = 'STOP_TYPING_MESSAGE_EVENT'
const BOT_SENDS_MESSAGE_EVENT = 'BSERVER_SENDS_MESSAGE_EVENT'
const COMPLETE_TASK_EVENT = 'COMPLETE_TASK_EVENT'

module.exports = {
  USER_JOIN_CHAT_EVENT,
  USER_LEAVE_CHAT_EVENT,
  NEW_CHAT_MESSAGE_EVENT,
  SEND_MESSAGE_TO_BOT_EVENT,
  START_TYPING_MESSAGE_EVENT,
  STOP_TYPING_MESSAGE_EVENT,
  BOT_SENDS_MESSAGE_EVENT,
  COMPLETE_TASK_EVENT
}