# This workflow is based on the one from Docker's documentation

name: CI to Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/trollbot:latest
          
      - name: Build and push rasa
        id: docker_build_rasa
        uses: docker/build-push-action@v2
        with:
          context: ./backend/rasa
          file: ./backend/rasa/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/trollbot-rasa:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
