name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend
        run: npm ci
        working-directory: backend
      - name: Lint backend
        run: npm run lint
        working-directory: backend
      - name: Test backend
        run: npm test
        working-directory: backend
      - name: Install frontend
        run: npm ci
        working-directory: frontend
      - name: Lint frontend
        run: npm run lint
        working-directory: frontend
      - name: Test frontend
        run: npm test
        working-directory: frontend
      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
