name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend
        run: npm ci
        working-directory: backend
      - name: Lint backend
        run: npm run lint
        working-directory: backend
      - name: Test backend
        run: npm test backend/tests
        env:
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
        working-directory: backend
      - name: Install frontend
        run: npm ci
        working-directory: frontend
      - name: Lint frontend
        run: npm run lint
        working-directory: frontend
      - name: Test frontend
        run: npm test
        working-directory: frontend
      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          working-directory: backend
  rasa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install rasa
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
        working-directory: ./rasa
      - name: Train rasa
        run: rasa train
        working-directory: ./rasa